name: Build core APK for pre release
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"

      # Optimización del caché de Gradle para compilaciones más rápidas
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Accept SDK licenses
        run: yes | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --licenses

# Genera el Keystore y lo coloca tanto en la raíz como en /app
      - name: Create fallback debug keystore
        run: |
          keytool -genkey -v -keystore test.jks -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
          cp test.jks app/test.jks
          
          # Configura keystore.properties sin prefijo de carpeta
          echo "storeFile=test.jks" > keystore.properties
          echo "storePassword=android" >> keystore.properties
          echo "keyAlias=androiddebugkey" >> keystore.properties
          echo "keyPassword=android" >> keystore.properties
          
          # Copia la misma configuración dentro de /app por si el subproyecto la busca aislada
          cp keystore.properties app/keystore.properties
      - name: Get date-time string
        id: datetime
        run: |
          DATE_TAG=$(date +'%Y-%m-%d_%H-%M-%S')
          echo "date_tag=$DATE_TAG" >> $GITHUB_ENV

      # Compilación de la variante Core
      - name: Build core userdebug APK
        run: ./gradlew assembleCoreUserdebug -x test -x lint --build-cache --parallel

      # Subir el APK como Artefacto (en lugar de crear la Pre-release)
      - name: Upload Core APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: core-userdebug-apk-${{ env.date_tag }}
          path: app/build/outputs/apk/core/userdebug/*.apk
          retention-days: 7 # Tiempo que se conservará el archivo en GitHub
